package kg.kundoluk.school.model.enums;

public enum SchoolOrganizationType {
    GENERAL_MIDDLE_SCHOOL,
    GYMNASIUM_SCHOOL,
    INNOVATIVE_GYMNASIUM_SCHOOL,
    GENERAL_MIDDLE_GYMNASIUM_SCHOOL,
    BOARDING_SCHOOL,
    COMPLETE_HIGH_SCHOOL,
    NOT_COMPLETE_HIGH_SCHOOL,
    HIGH_SCHOOL,
    RESIDENTIAL_BOARDING_SCHOOL,
    GENERAL_PRIMARY_SCHOOL,
    GENERAL_BASIC_SCHOOL,
    BASIC_SCHOOL,
    LYCEUM_BOARDING_SCHOOL,
    COLLEGE,
    EDUCATIONAL_COMPLEX
}
